### ISSUE TITLE
NoMethodError: undefined method `instance' for Capistrano::Configuration:Class

### ISSUE THREAD

**Issue by chrchr** [pitluga/supply_drop#64]
I have require 'supply_drop' at the top of deploy.rb, and otherwise it is a completely vanilla brand new 'cap install' setup.

Here is a trace: https://gist.github.com/chrchr/a41a7b662c25840ddbfe

**Comment by daachi** [comment]
I think you're running into a known issue, mitigated by https://github.com/pitluga/supply_drop/pull/63

Try adding it to your Capfile and see if that doesn't get you going.

**Comment by prachetasp** [comment]
Also 0.17.0 won't work with Cap3. You need to bump your supply_drop version to v1.0.0.beta1 or above. Most recent version is 1.0.0.beta2. Hope that helps!

**Comment by chrchr** [comment]
Yep. I was running 0.17 against Cap 3. That seems to have been the problem. Thanks!
